import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
import { CalendarIcon, Plus, Trash2, DollarSign, AlertTriangle, CheckCircle } from 'lucide-react';
import { format, addWeeks, isAfter } from 'date-fns';
import { useToast } from '@/hooks/use-toast';

// Updated interface to match database schema exactly
interface PaymentSchedule {
  id?: string; // Optional for new payments, will be generated by database
  name: string;
  amount: number;
  due_date: Date;
  description: string;
  status: 'pending' | 'paid' | 'overdue' | 'cancelled';
  phaseId?: string; // Optional reference to associated phase
}

interface Phase {
  id: string;
  name: string;
  isPaymentMilestone: boolean;
  start_date: Date | null;
  end_date: Date | null;
}

interface PaymentScheduleStepProps {
  data: PaymentSchedule[];
  phases: Phase[];
  totalBudget: number;
  currency: string;
  onUpdate: (data: PaymentSchedule[]) => void;
}

const paymentTemplates = [
  {
    name: 'Standard (25% - 50% - 25%)',
    description: 'Common payment schedule for most projects',
    schedule: [
      { name: 'Project Kickoff', percentage: 25, description: 'Initial payment upon project start' },
      { name: 'Mid-Project Milestone', percentage: 50, description: 'Payment at 50% project completion' },
      { name: 'Project Completion', percentage: 25, description: 'Final payment upon delivery' }
    ]
  },
  {
    name: 'Conservative (50% - 30% - 20%)',
    description: 'Higher upfront payment for cash flow',
    schedule: [
      { name: 'Project Start', percentage: 50, description: 'Large upfront payment' },
      { name: 'Development Complete', percentage: 30, description: 'Payment after main development' },
      { name: 'Final Delivery', percentage: 20, description: 'Final payment after testing and launch' }
    ]
  },
  {
    name: 'Milestone-Based',
    description: 'Equal payments for each major milestone',
    schedule: [
      { name: 'Design Approval', percentage: 20, description: 'Payment after design phase completion' },
      { name: 'Development Phase 1', percentage: 25, description: 'First development milestone' },
      { name: 'Development Phase 2', percentage: 25, description: 'Second development milestone' },
      { name: 'Testing Complete', percentage: 15, description: 'Payment after QA completion' },
      { name: 'Final Launch', percentage: 15, description: 'Final payment after successful launch' }
    ]
  }
];

export function PaymentScheduleStep({ data, phases, totalBudget, currency, onUpdate }: PaymentScheduleStepProps) {
  const { toast } = useToast();
  const [payments, setPayments] = useState<PaymentSchedule[]>(data);
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [newPayment, setNewPayment] = useState<Omit<PaymentSchedule, 'status'>>({
    name: '',
    amount: 0,
    due_date: new Date(),
    description: '',
    phaseId: ''
  });

  useEffect(() => {
    setPayments(data);
  }, [data]);

  const validatePayment = (payment: Omit<PaymentSchedule, 'status'>): string | null => {
    if (!payment.name.trim()) {
      return 'Payment name is required';
    }
    if (payment.amount <= 0) {
      return 'Amount must be a positive number';
    }
    if (!isAfter(payment.due_date, new Date())) {
      return 'Due date must be in the future';
    }
    return null;
  };

  const applyTemplate = (templateIndex: number) => {
    const template = paymentTemplates[templateIndex];
    const milestonePhases = phases.filter(phase => phase.isPaymentMilestone);
    
    let startDate = new Date();
    
    const newPayments: PaymentSchedule[] = template.schedule.map((item, index) => {
      const amount = Math.round((totalBudget * item.percentage) / 100);
      
      // Calculate due date based on phase progression
      let dueDate = startDate;
      if (index < milestonePhases.length) {
        const phase = milestonePhases[index];
        // Use phase end_date if available, otherwise space evenly
        if (phase.end_date) {
          dueDate = new Date(phase.end_date);
        } else {
          // Fallback: space payments 2 weeks apart
          dueDate = addWeeks(startDate, (index + 1) * 2);
        }
      } else {
        // If more payments than milestone phases, space them evenly
        dueDate = addWeeks(startDate, (index + 1) * 2);
      }

      return {
        name: item.name,
        amount,
        due_date: dueDate,
        phaseId: index < milestonePhases.length ? milestonePhases[index].id : '',
        description: item.description,
        status: 'pending' as const
      };
    });

    setPayments(newPayments);
    onUpdate(newPayments);
  };

  const addPayment = () => {
    const validationError = validatePayment(newPayment);
    if (validationError) {
      toast({
        title: "Validation Error",
        description: validationError,
        variant: "destructive",
      });
      return;
    }

    const payment: PaymentSchedule = {
      ...newPayment,
      status: 'pending'
    };

    const updatedPayments = [...payments, payment];
    setPayments(updatedPayments);
    onUpdate(updatedPayments);
    
    // Reset form
    setNewPayment({
      name: '',
      amount: 0,
      due_date: addWeeks(new Date(), 2), // Default to 2 weeks from now
      description: '',
      phaseId: ''
    });
    setIsAddDialogOpen(false);
    
    toast({
      title: "Payment Added",
      description: `Payment "${payment.name}" has been added to the schedule.`,
    });
  };

  const updatePayment = (index: number, updates: Partial<PaymentSchedule>) => {
    const updatedPayments = payments.map((payment, i) =>
      i === index ? { ...payment, ...updates } : payment
    );
    setPayments(updatedPayments);
    onUpdate(updatedPayments);
  };

  const removePayment = (index: number) => {
    const payment = payments[index];
    const updatedPayments = payments.filter((_, i) => i !== index);
    setPayments(updatedPayments);
    onUpdate(updatedPayments);
    
    toast({
      title: "Payment Removed",
      description: `Payment "${payment.name}" has been removed from the schedule.`,
    });
  };

  const totalScheduledAmount = payments.reduce((sum, payment) => sum + payment.amount, 0);
  const remainingBudget = totalBudget - totalScheduledAmount;
  const milestonePhases = phases.filter(phase => phase.isPaymentMilestone);

  const getPhaseById = (phaseId: string) => {
    return phases.find(phase => phase.id === phaseId);
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: currency || 'USD'
    }).format(amount);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'paid': return 'bg-green-500';
      case 'pending': return 'bg-yellow-500';
      case 'overdue': return 'bg-red-500';
      case 'cancelled': return 'bg-gray-500';
      default: return 'bg-blue-500';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between">
        <div>
          <h3 className="text-lg font-medium">Payment Schedule Setup</h3>
          <p className="text-sm text-muted-foreground">
            Create payment milestones tied to project phases and timeline
          </p>
        </div>
        
        <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              Add Payment
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[500px]">
            <DialogHeader>
              <DialogTitle>Add New Payment</DialogTitle>
              <DialogDescription>
                Create a new payment milestone for the project.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div>
                <Label htmlFor="payment-name">Payment Name *</Label>
                <Input
                  id="payment-name"
                  value={newPayment.name}
                  onChange={(e) => setNewPayment({ ...newPayment, name: e.target.value })}
                  placeholder="e.g., Project Kickoff Payment"
                />
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="payment-amount">Amount ({currency}) *</Label>
                  <Input
                    id="payment-amount"
                    type="number"
                    value={newPayment.amount || ''}
                    onChange={(e) => setNewPayment({ ...newPayment, amount: parseFloat(e.target.value) || 0 })}
                    placeholder="0"
                    min="0.01"
                    step="0.01"
                  />
                </div>
                <div>
                  <Label>Due Date *</Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className="w-full justify-start text-left font-normal"
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {newPayment.due_date ? format(newPayment.due_date, "MMM d, yyyy") : "Select date"}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={newPayment.due_date}
                        onSelect={(date) => date && setNewPayment({ ...newPayment, due_date: date })}
                        initialFocus
                        disabled={(date) => date < new Date()}
                      />
                    </PopoverContent>
                  </Popover>
                </div>
              </div>

              <div>
                <Label htmlFor="payment-phase">Associated Phase (Optional)</Label>
                <Select
                  value={newPayment.phaseId}
                  onValueChange={(value) => setNewPayment({ ...newPayment, phaseId: value })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select a phase..." />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">No specific phase</SelectItem>
                    {milestonePhases.map((phase) => (
                      <SelectItem key={phase.id} value={phase.id}>
                        {phase.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="payment-description">Description</Label>
                <Textarea
                  id="payment-description"
                  value={newPayment.description}
                  onChange={(e) => setNewPayment({ ...newPayment, description: e.target.value })}
                  placeholder="Description of what triggers this payment..."
                  rows={3}
                />
              </div>
            </div>

            <DialogFooter>
              <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>
                Cancel
              </Button>
              <Button 
                onClick={addPayment}
                disabled={!newPayment.name.trim() || newPayment.amount <= 0}
              >
                Add Payment
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      {/* Budget Overview */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-2">
              <DollarSign className="h-5 w-5 text-primary" />
              <div>
                <div className="text-xl font-bold">{formatCurrency(totalBudget)}</div>
                <div className="text-sm text-muted-foreground">Total Budget</div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-2">
              <CheckCircle className="h-5 w-5 text-primary" />
              <div>
                <div className="text-xl font-bold">{formatCurrency(totalScheduledAmount)}</div>
                <div className="text-sm text-muted-foreground">Scheduled</div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-2">
              <div className={`h-5 w-5 rounded-full ${remainingBudget < 0 ? 'bg-red-500' : remainingBudget > 0 ? 'bg-yellow-500' : 'bg-green-500'}`} />
              <div>
                <div className={`text-xl font-bold ${remainingBudget < 0 ? 'text-red-600' : remainingBudget > 0 ? 'text-yellow-600' : 'text-green-600'}`}>
                  {formatCurrency(remainingBudget)}
                </div>
                <div className="text-sm text-muted-foreground">Remaining</div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-2">
              <CalendarIcon className="h-5 w-5 text-primary" />
              <div>
                <div className="text-xl font-bold">{payments.length}</div>
                <div className="text-sm text-muted-foreground">Payments</div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Budget Warnings */}
      {remainingBudget < 0 && (
        <Card className="border-red-500 bg-red-50">
          <CardContent className="p-4">
            <div className="flex items-center gap-2 text-red-700">
              <AlertTriangle className="h-5 w-5" />
              <span className="font-medium">Over Budget</span>
            </div>
            <p className="text-sm text-red-600 mt-1">
              Scheduled payments exceed total budget by {formatCurrency(Math.abs(remainingBudget))}. Please adjust payment amounts.
            </p>
          </CardContent>
        </Card>
      )}

      {remainingBudget > 1000 && (
        <Card className="border-yellow-500 bg-yellow-50">
          <CardContent className="p-4">
            <div className="flex items-center gap-2 text-yellow-700">
              <AlertTriangle className="h-5 w-5" />
              <span className="font-medium">Unallocated Budget</span>
            </div>
            <p className="text-sm text-yellow-600 mt-1">
              {formatCurrency(remainingBudget)} is not yet allocated to payment milestones.
            </p>
          </CardContent>
        </Card>
      )}

      {/* Payment Templates */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Payment Templates</CardTitle>
          <CardDescription>
            Quick-start templates for common payment schedules
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {paymentTemplates.map((template, index) => (
              <Card key={index} className="cursor-pointer hover:bg-accent" onClick={() => applyTemplate(index)}>
                <CardContent className="p-4">
                  <div className="space-y-2">
                    <div className="font-medium">{template.name}</div>
                    <div className="text-sm text-muted-foreground">{template.description}</div>
                    <div className="flex flex-wrap gap-1">
                      {template.schedule.map((item, i) => (
                        <Badge key={i} variant="outline" className="text-xs">
                          {item.percentage}%
                        </Badge>
                      ))}
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Payment Schedule List */}
      {payments.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Payment Schedule</CardTitle>
            <CardDescription>
              Manage payment amounts, dates, and associated phases
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {payments.map((payment, index) => (
              <div key={index} className="p-4 border rounded-lg space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <Badge variant="outline">Payment {index + 1}</Badge>
                    <div className={`w-3 h-3 rounded-full ${getStatusColor(payment.status)}`} />
                    <span className="text-lg font-semibold">{formatCurrency(payment.amount)}</span>
                    <Badge variant="secondary" className="capitalize">
                      {payment.status}
                    </Badge>
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => removePayment(index)}
                    className="text-red-500 hover:text-red-700"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                  <div>
                    <Label>Payment Name</Label>
                    <Input
                      value={payment.name}
                      onChange={(e) => updatePayment(index, { name: e.target.value })}
                      placeholder="e.g., Project Kickoff Payment"
                    />
                  </div>
                  <div>
                    <Label>Amount ({currency})</Label>
                    <Input
                      type="number"
                      value={payment.amount}
                      onChange={(e) => updatePayment(index, { amount: parseFloat(e.target.value) || 0 })}
                      min="0.01"
                      step="0.01"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                  <div>
                    <Label>Due Date</Label>
                    <Popover>
                      <PopoverTrigger asChild>
                        <Button
                          variant="outline"
                          className="w-full justify-start text-left font-normal"
                        >
                          <CalendarIcon className="mr-2 h-4 w-4" />
                          {payment.due_date ? format(payment.due_date, "MMM d, yyyy") : "Select date"}
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0">
                        <Calendar
                          mode="single"
                          selected={payment.due_date}
                          onSelect={(date) => date && updatePayment(index, { due_date: date })}
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                  </div>
                  <div>
                    <Label>Status</Label>
                    <Select
                      value={payment.status}
                      onValueChange={(value: any) => updatePayment(index, { status: value })}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="pending">Pending</SelectItem>
                        <SelectItem value="paid">Paid</SelectItem>
                        <SelectItem value="overdue">Overdue</SelectItem>
                        <SelectItem value="cancelled">Cancelled</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div>
                  <Label>Associated Phase (Optional)</Label>
                  <Select
                    value={payment.phaseId}
                    onValueChange={(value) => updatePayment(index, { phaseId: value })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select a phase..." />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="">No specific phase</SelectItem>
                      {milestonePhases.map((phase) => (
                        <SelectItem key={phase.id} value={phase.id}>
                          {phase.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {payment.phaseId && getPhaseById(payment.phaseId) && (
                    <div className="mt-1 text-xs text-muted-foreground">
                      Linked to phase: {getPhaseById(payment.phaseId)?.name}
                    </div>
                  )}
                </div>

                <div>
                  <Label>Payment Description</Label>
                  <Textarea
                    value={payment.description}
                    onChange={(e) => updatePayment(index, { description: e.target.value })}
                    placeholder="Description of what triggers this payment..."
                    rows={2}
                  />
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      {payments.length === 0 && (
        <Card>
          <CardContent className="text-center py-12">
            <DollarSign className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-medium mb-2">No Payment Schedule</h3>
            <p className="text-muted-foreground mb-4">
              Add payment milestones or use a template to get started.
            </p>
            <Button onClick={() => setIsAddDialogOpen(true)}>
              <Plus className="h-4 w-4 mr-2" />
              Add First Payment
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}