// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edkaeoduyywdfpierfbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVka2Flb2R1eXl3ZGZwaWVyZmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTU2NzIsImV4cCI6MjA3MDk3MTY3Mn0.W8nVCqPObVgLu64bXX5v9dBARrBzCYhoyD0a7c3MLpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});